"""empty message

Revision ID: 727de7210269
Revises: 5deae6bf4b4d
Create Date: 2021-05-30 16:04:01.313328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727de7210269'
down_revision = '5deae6bf4b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'base64')
    # ### end Alembic commands ###
