"""empty message

Revision ID: 847336de0eee
Revises: 
Create Date: 2021-06-10 16:49:05.698310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847336de0eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('hue_median', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=128), nullable=True),
    sa.Column('growth', sa.String(length=128), nullable=True),
    sa.Column('variant', sa.String(length=128), nullable=True),
    sa.Column('replicate', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
