"""empty message

Revision ID: 920ddbb0cb31
Revises: 
Create Date: 2021-06-03 16:10:47.992093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920ddbb0cb31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('hue_circular_mean', sa.Integer(), nullable=True),
    sa.Column('hue_circular_std', sa.Integer(), nullable=True),
    sa.Column('hue_median', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
