"""measurements table

Revision ID: ad69291f663e
Revises: 
Create Date: 2021-05-12 22:13:59.084923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad69291f663e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('hue_circular_mean', sa.Integer(), nullable=True),
    sa.Column('hue_circular_std', sa.Integer(), nullable=True),
    sa.Column('hue_median', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
